# Generated by Django 4.1.6 on 2023-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='user_story_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
