# Generated by Django 4.1.7 on 2023-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='backlog_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
