# Generated by Django 4.1.7 on 2023-04-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='backlog_id',
            field=models.ForeignKey(db_column='backlog_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='app.proyecto'),
            preserve_default=False,
        ),
    ]
