# Generated by Django 4.1.7 on 2023-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sprint_backlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_real',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio_real',
            field=models.DateField(),
        ),
    ]
