# Generated by Django 4.1.7 on 2023-05-05 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_proyecto_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="estado",
        ),
    ]
