# Generated by Django 4.1.7 on 2023-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
