# Generated by Django 4.1.7 on 2023-04-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_proyecto_backlog_id'),
        ('app', '0002_userstory_user_story_name'),
        ('app', '0004_alter_sprint_fecha_fin_real_and_more'),
    ]

    operations = [
    ]
