# Generated by Django 4.1.6 on 2023-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='usuario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
