# Generated by Django 4.1.6 on 2023-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userstory_fecha_inicio'),
        ('app', '0005_userstory_usuario'),
    ]

    operations = [
    ]
