# Generated by Django 4.1.7 on 2023-04-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20230425_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
