# Generated by Django 4.1.6 on 2023-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20230507_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='usuario',
        ),
    ]
