# Generated by Django 4.1.6 on 2023-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_userstory_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
