# Generated by Django 4.1.6 on 2023-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sprint_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
