# Generated by Django 4.1.6 on 2023-06-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sprint_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioproyecto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
