# Generated by Django 4.1.6 on 2023-06-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usuarioproyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='id_usu_proy_rol',
            field=models.ForeignKey(db_column='id_usu_proy_rol', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.usuarioproyecto'),
        ),
    ]
