# Generated by Django 4.1.6 on 2023-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userstory_id_usu_proy_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
