# Generated by Django 4.1.7 on 2023-06-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_proyecto_fecha_fin_real_proyecto_fecha_inicio_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
    ]
