# Generated by Django 4.1.7 on 2023-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_userstory_id_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='fecha_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.CharField(blank=True, default='Yo como [perfil_usuario] necesito [funcionalidad] para [objetivo de la funcionalidad])', max_length=200, null=True),
        ),
    ]
